server:
  port: 9005
security:
  basic:
    enable: false
management:
  security:
    enabled: false
spring:
  cloud:
    config:
      enabled: true
  data:
    mongodb:
      uri: mongodb://db-mongo:27017/bdproyecto1
      #host: localhost
      #port: 27017
      #database: bdproyecto1
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://service-eureka-server:8761/eureka/