server:
  port: 9004
security:
  basic:
    enable: false
management:
  security:
    enabled: false
spring:
  cloud:
    config:
      enabled: true
  data:
    mongodb:
      uri: mongodb://db-mongo:27017/bdproyecto1
      #host: localhost
      #port: 27017
      #database: bdproyecto1
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: virtual-wallet-listener-group
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://service-eureka-server:8761/eureka/
resilience4j:
  circuitbreaker:
    instances:
      ms-customers-client:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s 