server:
  port: 9001
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZoraidaYasmin/repo-demo-proyecto4.git
          search-paths: config-data
          default-label: ${GIT_BRANCH}